Дизайн
themikhailova/def_det_n_class pull request #1
Opened 2024-12-10 07:53 UTC by leriagit

Изменения в ветке designer

2024-12-10 08:24 UTC, SeriousBanan requested changes

2024-12-10 08:24 UTC, SeriousBanan commented on design/design.ui
> +  <widget class="QWidget" name="centralwidget">
У тебя тут всё в одном грид лейауте. Мы обсуждали что ты разобьёшь на три отдельных виджета

2024-12-10 10:11 UTC, leriagit commented on design/design.ui
> +  <widget class="QWidget" name="centralwidget">
Исправлено, см. коммит [4a03ec5](https://github.com/themikhailova/def_det_n_class/pull/1/commits/4a03ec5)
https://github.com/themikhailova/def_det_n_class/pull/1/commits/4a03ec56b3f83fa3f4b320228ea02a661dc2dff1

2024-12-10 13:34 UTC, leriagit commented on design/design.ui
> +  <widget class="QWidget" name="centralwidget">
d8ddbc189de0dab0a75b24d45084e2f2f6d20507

2024-12-11 11:01 UTC, SeriousBanan requested changes

2024-12-11 11:01 UTC, SeriousBanan commented on design/main.py
> +        super(MainApp, self).__init__()
здесь просто `super().__init__()`

В питоне уже много лет не нужно писать аргументы функции super

2024-12-11 11:01 UTC, SeriousBanan commented on design/main.py
> +        file_name = os.path.basename(self.selected_file)
Для работы с путями в системе используй класс `Path` из `pathlib` а не `os`

2024-12-11 11:01 UTC, SeriousBanan commented on design/main.py
> +        try:
Внутри блока `try` нужно писать как можно меньше кода, чтобы отлавливать более специфичные ошибки

В данном случае ты пытаешься скопировать файл. Это то место где может появится ошибка. А вывод сообщений это уже если ошибки не было и в них не может быть ошибок связанных с сохранением файла, а только с тем как код написан. Поэтому это нужно вынести

Можно сделать так:
```py
try:
    copy

except Exception as exc:
    print error

else:
    print succecc
```

2024-12-11 11:01 UTC, SeriousBanan commented on design/main.py
> +        except Exception as e:
Никогда не называй переменные одной или двумя буквами. Ошибки обычно называются `exc`

2024-12-11 11:01 UTC, SeriousBanan commented on design/main.py
> +        files = [f for f in os.listdir(directory) if f.endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]
Тут лучше использовать регулярные выражения для проверки типов файлов. Заведи переменную одтельную в котором будет регулярка под изображения и используй её для проверки

Пример из интернета:
```py
import re
from pathlib import Path
basepath = Path('C:/Users/user/Pictures')
pattern = '.*(jpe?g|png)'

matching_files = [p for p in basepath.iterdir() if re.match(pattern, p.name]
```

2024-12-11 11:01 UTC, SeriousBanan commented on design/main.py
> +        model = QtCore.QStringListModel()
Модель нужно создавать при инициализации класса, один раз назначать её виджету и дальше обновлять данные в ней, а не создавать каждый раз новую модель

2024-12-11 11:01 UTC, SeriousBanan commented on design/requirements.txt
> +click==8.1.7
В реквайрментах пиши `~=` вместо `==`

2024-12-12 12:25 UTC, leriagit commented on design/main.py
> +        super(MainApp, self).__init__()
c5afc9286bc2b95ca62c06f1707d89307d04fa6d

2024-12-12 12:37 UTC, leriagit commented on design/main.py
> +        file_name = os.path.basename(self.selected_file)
55716e4b52eb0f7bea9dac095de37ae277bd634c - конечный вариант всех исправлений

2024-12-16 14:49 UTC, SeriousBanan requested changes
И удали папку .idea и добавь её в .gitignore

2024-12-16 14:49 UTC, SeriousBanan commented on design/main.py
> +    def load_files_from_directory(self, directory):
По логике модель с файлами в данном классе одна и получается источник данных тоже должен быть один

Этот источник у тебя - `self.current_directory`. А модель - `self.model`. Эти сущности в программе должны быть жёстко связанны, потому что данные в них одни и теже циркулируют и никак не делятся.

А эта функция у тебя получает произвольную директорию и заносит эти данные в модель класса. Получается теряется связь между источником и назначением данных (хоть ты и вызываешь эту функцию как только обновила `self.current_directory`.

Есть два ваианта как вернуть связность:
1. Сделать чтобы функция возвращала список с именами файлов. Тогда ты в месте где эту функцию вызываешь сначала обновляешь `self.current_directory`, потом через эту функцию получаешь список файлов в директории и потом там же где ты присваивала `self.current_directory` ты обновляешь `self.model`
2. переименовать функцию в `load_files_from_current_directory` и убрать аргумент директории (использовать внутри функции `self.current_directory`

Мне сейчас кажется проще и лучше сделать второй вариант. Но в будущем лучше делать как я написал в первом варианте и выносить такие функции в модуль с утилитами

2024-12-16 14:49 UTC, SeriousBanan commented on design/main.py
> +        try:
Почему тут try exept?

2024-12-16 14:49 UTC, SeriousBanan commented on design/main.py
> +        files = [f for f in os.listdir(directory) if f.endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]
Сделай `image_pattern` константой на уровне модуля. Она не особо относится к классу программы логически

2024-12-17 13:51 UTC, leriagit commented on design/main.py
> +        files = [f for f in os.listdir(directory) if f.endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp'))]
3cdb35fd0930c5f9595849a0e3a52936cd99179c

2024-12-18 08:27 UTC, SeriousBanan approved these changes

2024-12-18 08:27 UTC, merged