functionality of the buttons
themikhailova/def_det_n_class pull request #2
Opened 2024-12-26 16:51 UTC by leriagit

все изменения функционала приложения

2025-01-09 13:50 UTC, SeriousBanan requested changes

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +import pandas as pd
Не надо сокращать названия библиотек. Это пошло от аналитиков данных которые быстро пишут одноразовый код

Используй везде `pandas`

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        self.ui.browseButton.clicked.connect(self.select_directory)
Сейчас можно так оставить, но на будущее лучше делать одинаковые названия кнопок и действий которые они делают

Если метод называется `reject` то и кнопка дложна быть`reject_button`. Иначе будет путаница

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        if template_data.get("Директория эталонов"):
`.get` используется когда нам нужно получить что-то из структуры данных или значение по умолчанию если такого ключа нет.

Когда мы ходим проверить есть ли что-то по данному ключу, то нужно делать:

```py
if "Директория эталонов" in template_data:
    ...
```

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        name = self.ui.table.item(0, 0).text() if self.ui.table.item(0, 0) else ""
Вообще не очень хорошо использовать магические числа, особенно когда у тебя в одном месте дублируется оно несколько раз. Из-за этого могут ошибки появляться, которые турдно найти (например где-то вместо 0 тут будет 1)

Лучше сделай константу для айтема и уже с ним работай:

```py
name_item = self.ui.table.item(0, 0)
name = name_item.text() if name_item else ""
```

И тоже самое для `code`

2025-01-09 13:50 UTC, SeriousBanan commented on design/design.py
> +class Ui_AddTemplateDialog(object):
Если ты используешь этот темплейт для диалоговых окон добавления и изменения, то этот класс скорее должен называться: `Ui_SelectTemplateDialog`

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +class AddTemplateDialog(QtWidgets.QDialog):
У тебя классы `AddTemplateDialog` и `EditTemplateDialog` отличаются только тем что у `edit` есть предзаполненые данные. В остальном эти классы идентичны как по назначению так и по реализации.

Ни в коем случае в коде не должно быть копипаста, потому что потом при добавлении нового функционала нужно будет менять код в двух местах одновременно, что очень сильно повышает вероятность ошибки.

Ты можешь объединить оба класса в один `SelectTemplateDialog` в котором будет необязательный аргумент в `__init__(template_data=None)`.

Соответственно когда там `None` ты ничего не делаешь, а в противном случае ты выполняешь добавочную логику, которая у тебя есть в `EditTemplateDialog`

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        return {"name": name, "code": code, "directory": directory}
Появляется путаница из-за того что в диалоговом окне изменения ты использовала ключи на русском, а тут на англиском. Нужно выбрать один стиль и работать с ним. Раз уж у тебя в таблице данные на русском я предлагаю сейчас использовать ключи тоже на русском

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        if not name or not code or not directory:
Эта проверка у тебя должна быть на моменте когда пользователь нажимает `save_button` а не когда окно уже закрылось и происходит получение данных

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        if not name or not code or not directory:
И как следствие у тебя метод `get_template_data` всегда будет возвращать валидный словарь

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +            if template_data:  # Проверяем, что данные корректно извлечены
Выше писал что нужно из `get_template_data` убрать проверку заполнености и всегда возвращать валидный словарь. Соответственно тут не нужна проверка

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +            return
Тут не нужно делать `return` потому что это прерывает действие на половине пути и состояние станвоится несогласованным

Нужно либо делать проверку на наличие файлов в методе `on_set_directory_clicked` до того как начали меняться перменные которые в `self` храняться, либо не делать `return` тут и довести состояние до конца, где не будет изображений

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +            widget_width = self.ui.image_list.width() - 10  # Учитываем отступы
значение `10` нужно либо получать из свойств элемента, либо занести в константу с понятным названием

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        self.template_df = self.template_df[["Наименование", "Код изделия", "Директория эталонов"]]
Зачем тут эта строчка, если template_df и так содержит эти колонки?

2025-01-09 13:50 UTC, SeriousBanan commented on design/main.py
> +        self.template_df = self.load_template_file()
Удали из кода файл эксель файл и сделай при открытие приложения проверку на то существует ли файл. Если не существует, то в `self.template_df` будет создаваться пустой датафрейм с нужными колонками, а не подгружаться из файла

2025-01-15 12:20 UTC, leriagit commented on design/main.py
> +import pandas as pd
6abec602e34e9cb6e38540128d5601f037465ba5

2025-01-17 10:13 UTC, SeriousBanan commented on design/main.py
> +            return
Давай не будем добавлять текст в список который под itemы расчитан

Удали `self.ui.image_list.addItem("Нет изображений")`

На всякий случай, чтобы потом не было ошибок в будущем

2025-01-17 10:19 UTC, SeriousBanan commented on design/main.py
> +        self.template_df = self.load_template_file()
В `__init__`  не нужна проверка на существование файла и открытие его, ведь ты переделала функцию `load_template_file`. Просто вызови её

И файл эксельки не удалился из проекта. Удали файл с помощью `git rm`, потом добавь эксель файлы в .gitignore и закоментируй всё это

2025-01-17 16:50 UTC, leriagit commented on design/main.py
> +            return
e3b5fabeab129dd6573828b31019faf22f71109d

2025-01-17 16:55 UTC, leriagit commented on design/main.py
> +            widget_width = self.ui.image_list.width() - 10  # Учитываем отступы
aad093dab6bc5437dc5d9425b331a10c7720f293

2025-01-17 16:55 UTC, leriagit commented on design/main.py
> +        self.template_df = self.load_template_file()
e3b5fabeab129dd6573828b31019faf22f71109d

2025-01-20 10:35 UTC, SeriousBanan approved these changes

2025-01-20 10:35 UTC, merged